site_name: My Docs
site_description: Documentation for our awesome team
site_author: Your Name

theme:
  name: material

nav:
  - Home: index.md
  - About: about.md
  - Guidelines: guidelines.md

# CI/CD Installation Step (if used in GitHub Actions or similar)
extra:
  install_dependencies:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material